SHPDR-17 implemented set-style command and small fixes
pietrik123/shapedrawercpp pull request #22
Opened 2022-06-16 16:28 UTC by fokija

2022-06-16 17:13 UTC, pietrik123 requested changes

2022-06-16 17:13 UTC, pietrik123 commented on command.cc
> +        std::string availableSpecialChar = "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~";
what is it for ? do we need all of these for any command ?

2022-06-16 17:13 UTC, pietrik123 commented on command.cc
> +    std::string x = m_args[1];
please replace `x` with more decriptive variable name ?

2022-06-16 17:13 UTC, pietrik123 commented on command.cc
> +        int y = std::atoi(m_args[0].c_str());
please see a comment for `x` variable

2022-06-16 17:13 UTC, pietrik123 commented on command.cc
> +    char tempChar = x[0];
let's return `false` if the second parameter's length is more than 1 and inform the user that single character should be provided

2022-06-16 19:37 UTC, pietrik123 commented on command.cc
> +        std::string availableSpecialChar = "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~";
after we discussed, we should keep your change or we may use 
```
if (c > 32 && c < 127)
{
}
```

2022-06-19 13:42 UTC, pietrik123 approved these changes

2022-06-19 15:32 UTC, dante7867 approved these changes

2022-06-19 18:15 UTC, merged